spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}/${DATABASE_NAME:cqr-db}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write_dates_as_timestamps: true
    time-zone: America/Sao_Paulo
  config:
    import: optional:file:.env[.properties]

jwt:
  token:
    secret: ${JWT_SECRET:secret}
    expiration-time-in-days: ${JWT_EXPIRATION_TIME:7}
    issuer: ${JWT_ISSUER:default}
  refresh-token:
    secret: ${JWT_SECRET_REFRESH:secretrefresh}
    expiration-time-in-hours: ${JWT_EXPIRATION_TIME_REFRESH:1}
    issuer: ${JWT_ISSUER_REFRESH:default}

security:
  no-auth-urls:
    - "/auth/**"

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "${FRONTEND_URL:http://localhost:3000}"
  allowed-methods:
    - "GET"
    - "POST"
    - "PUT"
    - "PATCH"
    - "DELETE"
    - "OPTIONS"
  allowed-headers:
    - "Authorization"
    - "Content-Type"
    - "Accept"
